# version: '3.8'

services:
  bot:
    container_name: wolfyz-upload-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - ./config:/app/config:ro
    working_dir: /app
