name: Deploy to VPS on push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4



#       - name: Copy project to VPS and deploy Docker
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.VPS_HOST }}
#           username: ${{ secrets.VPS_USER }}
#           key: ${{ secrets.VPS_SSH_KEY }}
#           source: "."
#           target: "~/wolfyzupload"

#       - name: SSH into VPS and restart Docker
#         uses: appleboy/ssh-action@v1.0.3
#         with:
#           host: ${{ secrets.VPS_HOST }}
#           username: ${{ secrets.VPS_USER }}
#           key: ${{ secrets.VPS_SSH_KEY }}
#           script: |
#             cd ~/wolfyzupload
#             docker compose down --remove-orphans
#             docker compose build --no-cache
#             docker compose up -d
